GET http://localhost:8080/api/restaurants

###

POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "hasheduser@test.com",
  "password":"test123"
}
###
GET http://localhost:8080/api/restaurants
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXNoZWR1c2VyQHRlc3QuY29tIiwiaWF0IjoxNzc3OTI0Mzc3LCJleHAiOjE3Nzc5Mjc5Nzd9._v9YSTA1u6jGtBmL0acbBwGDbCiu2DlwowGPHHHibpg
###
POST http://localhost:8080/api/orders?customerId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXNoZWR1c2VyQHRlc3QuY29tIiwiaWF0IjoxNzc4MDY0Mzg1LCJleHAiOjE3NzgwNjc5ODV9.jZ59fdTZOOq-59HYDHAHJVR6fy2mr8zRbv8Rw9rqZik
Content-Type: application/json

{
  "restaurantId": 1,
  "items": [
    {
      "menuItemId": 3,
      "quantity": 2
    }
  ]
}
###
POST http://localhost:8080/api/payments?orderId=1&amount=1700
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXNoZWR1c2VyQHRlc3QuY29tIiwiaWF0IjoxNzc4MDYyODY1LCJleHAiOjE3NzgwNjY0NjV9.16APaKfKzUMW8nWzP0c2BLA9CzWCE_c-XwBzwbbDHwY